web:
  image: dockergeneratedata_web
  command: /run.sh
  ports: 
    - "80:80"
  links:
    - mysql
mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: UnSecUr3dPassW0rd!
    MYSQL_DATABASE: generatedata
